name: home-assistant-toolbox
base: core20
version: '0.1' 
summary: Extend your Home Assistant (home-assistant-snap)
description: |
  Toolbox contains executables that extends functionality
  to you home-assistant-snap installation.

  The following tools are included:
    - cURL

  (More to come, and feel free to come up with suggestions!)

  Requires home-assistant-snap revision 71 or later!
grade: stable
confinement: strict 

slots:
  bin:
    interface: content
    content: executables
    source:
      read:
        - $SNAP/bin
        - $SNAP/etc
        - $SNAP/lib
        - $SNAP/usr

parts:
  home-assistant-toolbox:
    plugin: dump
    source: ./src
    source-type: local
    stage-packages:
      - curl
