name: home-assistant-toolbox
base: core20
version: '0.1' 
summary: Extend your Home Assistant (home-assistant-snap)
description: |
  Toolbox contains executables that extends functionality
  to you home-assistant-snap installation.

  The following tools are included:
    - cURL

grade: devel # must be 'stable' to release into candidate/stable channels
confinement: devmode # use 'strict' once you have the right plugs and slots

apps:
  curl:
    command: bin/curl

slots:
  bin:
    interface: content
    content: executables
    source:
      read:
        - $SNAP/bin

parts:
  home-assistant-toolbox:
    plugin: dump
    source: ./src
    source-type: local
    stage-packages:
      - curl
